<?php

namespace App\Swagger\Content;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'ContentPageInput', required: ['title', 'content', 'page_type'], properties: [new OA\Property(property: 'slug', type: 'string', example: 'about-us'), new OA\Property(property: 'title', type: 'string'), new OA\Property(property: 'navigation_title', type: 'string', nullable: true), new OA\Property(property: 'excerpt', type: 'string', nullable: true), new OA\Property(property: 'content', type: 'string'), new OA\Property(property: 'page_type', type: 'string', enum: ['about', 'contact', 'privacy_policy', 'terms', 'shipping_policy', 'returns_policy', 'custom']), new OA\Property(property: 'settings', type: 'object', nullable: true), new OA\Property(property: 'meta_title', type: 'string', nullable: true), new OA\Property(property: 'meta_description', type: 'string', nullable: true), new OA\Property(property: 'is_published', type: 'boolean'), new OA\Property(property: 'published_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'expires_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'applies_to_all_storefronts', type: 'boolean'), new OA\Property(property: 'storefront_ids', type: 'array', items: new OA\Items(type: 'string')), new OA\Property(property: 'display_order', type: 'integer', minimum: 0)])]
#[OA\Schema(schema: 'FaqCategoryInput', required: ['name'], properties: [new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'slug', type: 'string'), new OA\Property(property: 'description', type: 'string', nullable: true), new OA\Property(property: 'display_order', type: 'integer'), new OA\Property(property: 'is_active', type: 'boolean')])]
#[OA\Schema(schema: 'FaqInput', required: ['faq_category_id', 'question', 'answer'], properties: [new OA\Property(property: 'faq_category_id', type: 'string'), new OA\Property(property: 'question', type: 'string'), new OA\Property(property: 'answer', type: 'string'), new OA\Property(property: 'display_order', type: 'integer'), new OA\Property(property: 'is_published', type: 'boolean'), new OA\Property(property: 'published_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'expires_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'applies_to_all_storefronts', type: 'boolean'), new OA\Property(property: 'storefront_ids', type: 'array', items: new OA\Items(type: 'string'))])]
#[OA\Get(path: '/content-pages', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'page_type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'state', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'storefront_id', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', maximum: 100))], responses: [new OA\Response(response: 200, description: 'Paginated pages'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/content-pages', tags: ['Content Pages'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/ContentPageInput')), responses: [new OA\Response(response: 201, description: 'Created'), new OA\Response(response: 422, description: 'Validation error')])]
#[OA\Get(path: '/content-pages/{contentPage}', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Details')])]
#[OA\Patch(path: '/content-pages/{contentPage}', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/ContentPageInput')), responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Delete(path: '/content-pages/{contentPage}', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Soft deleted')])]
#[OA\Post(path: '/content-pages/{contentPage}/publish', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Published')])]
#[OA\Post(path: '/content-pages/{contentPage}/unpublish', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Unpublished')])]
#[OA\Post(path: '/content-pages/{contentPage}/duplicate', tags: ['Content Pages'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'contentPage', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(required: ['slug'], properties: [new OA\Property(property: 'slug', type: 'string')])), responses: [new OA\Response(response: 201, description: 'Duplicated')])]
#[OA\Get(path: '/faq-categories', tags: ['FAQ Categories'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Paginated categories')])]
#[OA\Post(path: '/faq-categories', tags: ['FAQ Categories'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/FaqCategoryInput')), responses: [new OA\Response(response: 201, description: 'Created')])]
#[OA\Get(path: '/faq-categories/{faqCategory}', tags: ['FAQ Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faqCategory', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Details')])]
#[OA\Patch(path: '/faq-categories/{faqCategory}', tags: ['FAQ Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faqCategory', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/FaqCategoryInput')), responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Delete(path: '/faq-categories/{faqCategory}', tags: ['FAQ Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faqCategory', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Soft deleted'), new OA\Response(response: 409, description: 'Category still has FAQs')])]
#[OA\Post(path: '/faq-categories/reorder', tags: ['FAQ Categories'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(content: new OA\JsonContent(required: ['ids'], properties: [new OA\Property(property: 'ids', type: 'array', items: new OA\Items(type: 'string'))])), responses: [new OA\Response(response: 200, description: 'Reordered')])]
#[OA\Get(path: '/faqs', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'faq_category_id', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'state', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'storefront_id', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Paginated FAQs')])]
#[OA\Post(path: '/faqs', tags: ['FAQs'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/FaqInput')), responses: [new OA\Response(response: 201, description: 'Created')])]
#[OA\Get(path: '/faqs/{faq}', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Details')])]
#[OA\Patch(path: '/faqs/{faq}', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/FaqInput')), responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Delete(path: '/faqs/{faq}', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Soft deleted')])]
#[OA\Post(path: '/faqs/{faq}/publish', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Published')])]
#[OA\Post(path: '/faqs/{faq}/unpublish', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Unpublished')])]
#[OA\Post(path: '/faqs/{faq}/duplicate', tags: ['FAQs'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'faq', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 201, description: 'Duplicated')])]
#[OA\Post(path: '/faqs/reorder', tags: ['FAQs'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(content: new OA\JsonContent(required: ['ids'], properties: [new OA\Property(property: 'ids', type: 'array', items: new OA\Items(type: 'string'))])), responses: [new OA\Response(response: 200, description: 'Reordered')])]
class ContentManagement {}
